# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0ecb5c22686cb74846b5406eea05c0902f50fddf9634f65ca283cc27bb566f3fb2654e5851eb14cb29a866ea8b8452cc99eab3d656357c94a014ab075a77c4b

test:
  secret_key_base: 4371b413516f11e3a6452612abfdca57b2e813083de9a38afd77ed3068359a2651fb084ef7cdc2e500b46a241396c957118052c446eb2414409b7c1347fa63f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
