# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63afdab0fcdbd753d4b232f5bfb5d23f9c4460aece69710c841f9b427c759d8554979fcea48e91856003471ecd628bfd209ac6fb69fa3f80f94b63fa7de2bbca

test:
  secret_key_base: 48fa8213a73d007877ca3a6c85f78308f733235a31df6d571aa947d5a14e9fbf467bf239e8427c020e55587b625952d00e048c85784a5463e4d37d2d4e036865

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
